### ISSUE TITLE
Wasted My Time, Atleast Write 'Not Working Now' or 'No Data Avaliable'

### ISSUE THREAD

**Issue by imlolman** [plibither8/delhi-metro-api#1]

**Comment by plibither8** [comment]
Hi, I must firstly say, the entitlement is strong on this one.

What's not working? Which data is not _available_?

Though I have mentioned very explicitly that this project is a **Work In Progress [WIP]**, I believe that the basic API and data retrieval is working as it should, just that the proper documentation is missing, which is the _in progress_ part.

Nevertheless, the following is the basic API documentation. You can get a better understanding of the paths [here](https://github.com/plibither8/delhi-metro-api/blob/master/routes/api.js).

* The base URL for the API is `https://api.delhimetro.ga`. All below mentioned endpoints are to be appended to this URL.

* All queries return a JSON, which can be appropriately parsed.

### Endpoints

#### 1. `GET /`
Returns list of all stations along with necessary details regarding it.

**Example:** [https://api.delhimetro.ga/](https://api.delhimetro.ga/)
```json
[
  {
    "name": "Adarsh Nagar",
    "mobile": 8800793122,
    "lines": [
      {
        "name": "Yellow Line",
        "lineId": 1,
        "stationId": 4,
        "distance": 4.7
      }
    ]
  },
  {
    "name": "AIIMS",
    "mobile": 8800793140,
    "lines": [
      {
        "name": "Yellow Line",
        "lineId": 1,
        "stationId": 22,
        "distance": 24.6
      }
    ]
  },
...
]
```

#### 2. `GET /lines/[:lineName]`
Returns details of all lines, name-wise if `lineName` parameter is not supplied. If present, returns details of the requested line.

**Example:** [https://api.delhimetro.ga/lines](https://api.delhimetro.ga/lines)
```json
[
  {
    "name": "Red Line",
    "id": 0,
    "stations": [
      {
        "name": "Shaheed Sthal(New Bus Adda)",
        "mobile": 0,
        "lines": [
          {
            "name": "Red Line",
            "lineId": 0,
            "stationId": 0,
            "distance": 0
          }
        ]
      },
      ...
	]
  },
  ...
]
```

**Example:** [https://api.delhimetro.ga/lines/red](https://api.delhimetro.ga/lines/red)
```json
{
  "name": "Red Line",
  "id": 0,
  "stations": [
    {
      "name": "Shaheed Sthal(New Bus Adda)",
      "mobile": 0,
      "lines": [
        {
          "name": "Red Line",
          "lineId": 0,
          "stationId": 0,
          "distance": 0
        }
      ]
    },
  ...
}
```

#### 3. `GET /stations/[:stationName]`
Returns details of all stations, if `stationName` parameter is not supplied (same as `GET /`). If present, returns details of the requested station.

**Example:** [https://api.delhimetro.ga/stations](https://api.delhimetro.ga/stations)

_Refer to `GET /`_


#### 3. `GET /list/[:listName]`
Returns an array just names of all stations and line-names, if `listName` parameter is not supplied.
`listName` can be either `stations` OR `lines`.
If present, returns details of the requested list.

**Example:** [https://api.delhimetro.ga/list](https://api.delhimetro.ga/list)
```json
{
  "lines": [
    "Red Line",
    "Yellow Line",
    "Blue Line",
    "Airport Express",
    "Green Line-Indrlok to Mundka",
    "Rapid",
    "Violet Line",
    "Magenta Line",
    "Pink Line",
    "Blue Line",
    "Green Line",
    "Aqua Line"
  ],
  "stations": [
    "Adarsh Nagar",
    "AIIMS",
    "Akshardham",
    ...
  ]
}
```
---
I have provided a quick gist of the API, the proper documentation will be worked upon later next month.

I'd also request you to supply more details (and be a bit less rough, even though I understand your situation) next time you open an issue on any repository. It will help both of us.

Thanks.

**Comment by imlolman** [comment]
Thanks, as I was not able to find the proper documentation and I was having Trouble to work with it, I was frustated. As I got everything above, thanks for quick response :).
